### ISSUE TITLE
@Comment field not recognized 

### ISSUE THREAD

**Issue by kaustubhmote** [Nagasaki45/bibo#70]
The field `@Comment` when present with capitalized "C" is not recognised correctly, and reading a library fails, as this is interpreted to be an entry type similar to `@Article`. 

There are 2 solutions to this issue:
1. `type_` can be defaulted to lowercase in `pybibs/pybibs.py:29`. This will not respect the case of the original entry.   
2. Whenever the type of the entry is checked, use `type_.lower()` instead of `type_`. The following lines will need to change: `pybibs/pybibs.py:40`, `pybibs/_internals.py:106` and `bibo/internals.py:181`. I would prefer this method, but am not sure if there are more places where these would be needed.

Both of the above methods work. I'll be happy to do a PR if you let me know your preference.

**Comment by Nagasaki45** [comment]
Great catch @kaustubhmote!

I will go with the 2nd option. Otherwise, writing to the database (the .bib file) will override all types to lowercase. I don't imagine people use the case of types in .bib files  in a meaningful way but you can never know :-)
A PR will be super welcome! [Check this out](https://bibo.readthedocs.io/en/latest/contribution.html) for some contribution guidelines.
