### ISSUE TITLE
Show unicode characters when listing entries 

### ISSUE THREAD

**Issue by harisont** [Nagasaki45/bibo#82]
Hi! Seems that this is the reference manager I was looking for, simple and effective :)

A problem I have with it, though, is that many of the names of the authors of the papers I read (are supposed to) contain unicode characters. In `.bib` files, they are usually represented with some sequence. For example "Gunlög" becomes `Gunl{\"o}g`. When I run `bibo list`, I would like to see the unicode chars corresponding to each sequence, whenever possible.

Is that something you can consider implementing?

**Comment by Nagasaki45** [comment]
Hi Arianna. Welcome :-)

Yeah, this is a very good idea! I don't think I have the time for this at the moment but if you do feel free to send an MR. Did you go through the code? Will be happy to help if you want some directions / explanations about how things currently implemented.

**Comment by harisont** [comment]
I haven't, but let's see if I have some time to take a look over the weekend.

**Comment by Nagasaki45** [comment]
Hi @harisont! Just pushed a new version (0.1.17) to PyPI that converts latex to unicode when listing entries. It convert both the citation and the "Search matched by" output (if you're not familiar with the feature try to search for something that is not in the citation, like a snippet from the abstract, name of publisher, etc). Please give it a go. I'm closing the ticket for now. Feel free to reopen if the fix is not to your liking :-)

Cheers,
Tom

**Comment by harisont** [comment]
Perfect! Thank you :D
